### ISSUE TITLE
Doesn't compile on Ubuntu 21.10

### ISSUE THREAD

**Issue by dsvensson** [QW-Group/mvdparser#16]
`temp_entities` is declared in the `qw_protocol.h` header file, and I guess imported in two places. Just adding a ultra-nasty ifndef-hack makes it compile and work. Don't know enough about the code place for a proper fix, but the declaration should probably be moved to some good place (if variables prefixed with `temp_` has good places), and the header file would declare it as extern or so.

```diff
diff --git a/src/qw_protocol.h b/src/qw_protocol.h
index 3a171de..ae74d69 100644
--- a/src/qw_protocol.h
+++ b/src/qw_protocol.h
@@ -587,7 +587,13 @@ typedef struct temp_entity_list_s
+#ifndef temp_entities
+#define temp_entities
 temp_entity_list_t	temp_entities;
+#else
+extern temp_entity_list_t	temp_entities;
+#endif
```

Compiler: `gcc (Ubuntu 11.2.0-7ubuntu2) 11.2.0`

```
[100%] Linking C executable mvdparser
/usr/bin/ld: CMakeFiles/mvdparser.dir/src/logger.c.o:(.bss+0x1040): multiple definition of `temp_entities'; CMakeFiles/mvdparser.dir/src/frag_parser.c.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/mvdparser.dir/src/main.c.o:(.bss+0x40): multiple definition of `temp_entities'; CMakeFiles/mvdparser.dir/src/frag_parser.c.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/mvdparser.dir/src/mvd_parser.c.o:(.bss+0x0): multiple definition of `temp_entities'; CMakeFiles/mvdparser.dir/src/frag_parser.c.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/mvdparser.dir/src/net_msg.c.o:(.bss+0x40): multiple definition of `temp_entities'; CMakeFiles/mvdparser.dir/src/frag_parser.c.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/mvdparser.dir/src/netmsg_parser.c.o:(.bss+0x0): multiple definition of `temp_entities'; CMakeFiles/mvdparser.dir/src/frag_parser.c.o:(.bss+0x0): first defined here
```

**Comment by tcsabina** [comment]
Hi @dsvensson ,

Thanks for the report. 
What toolchain do you use? How exactly are you trying to build the project? 

regards,
toma

**Comment by dsvensson** [comment]
`gcc (Ubuntu 11.2.0-7ubuntu2) 11.2.0` as mentioned,


```
mkdir build
cd build
cmake ..
make
````
